VSC React Client Test

###
# Create a new user
POST http://localhost:8000/api/subscribers/create
curl -X POST -H "Content-Type: application/json" -d '{"name": "linuxize", "phone": "0123456789"}' http://localhost:8000/api/subscribers/create
Content-Type: application/json
{
    "name": "linuxize",
    "phone": "0123456789"
}

###
# Create the same user with a different number
POST http://localhost:8000/api/subscribers/create
curl -X POST -H "Content-Type: application/json" -d '{"name": "linuxize", "phone": "1234567890"}' http://localhost:8000/api/subscribers/create
Content-Type: application/json
{
    "name": "linuxize",
    "phone": "1234567890"
}

###
# Get all records
GET http://localhost:8000/api/subscribers/
curl http://localhost:8000/api/subscribers/ -H "Accept: application/json"

###
# Get the name of the user by one of his phone numbers
GET http://localhost:8000/api/subscribers/:phone
curl http://localhost:8000/api/subscribers/0123456789 -H "Accept: application/json"

###

###
# Get phone numbers by subscriber name
GET http://localhost:8000/api/phones/:name
curl http://localhost:8000/api/phones/linuxize -H "Accept: application/json"
###

###
# Delete a subscriber with phone numbers assigned to it
POST https://localhost:8000/subscribers/delete/
curl -X POST -H "Content-Type: application/json" -d '{"name": "linuxize", "number": "1234567890"}' http://localhost:8000/api/subscribers/delete
{
    "name": "linuxize",
    "number": "0123456789"
}